# Generated by Django 2.2.1 on 2019-05-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercompany',
            table='user_company',
        ),
    ]
