# Generated by Django 2.2.1 on 2019-05-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_auto_20190519_2253'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercompany',
            table='tms_user_company',
        ),
    ]
