# Generated by Django 2.2.1 on 2019-05-21 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_auto_20190520_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.PositiveIntegerField()),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('merger_name', models.CharField(max_length=50)),
                ('code', models.PositiveSmallIntegerField()),
                ('zip_code', models.PositiveIntegerField()),
                ('lel', models.PositiveSmallIntegerField()),
                ('pinyin', models.CharField(max_length=50)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('bank_num', models.CharField(blank=True, max_length=50)),
                ('bank_person', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField()),
                ('contract_no', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('status', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ori_province', models.PositiveIntegerField()),
                ('ori_province_name', models.CharField(max_length=50)),
                ('ori_city', models.PositiveIntegerField()),
                ('ori_city_name', models.CharField(max_length=50)),
                ('ori_area', models.PositiveIntegerField()),
                ('ori_area_name', models.CharField(max_length=50)),
                ('des_province', models.PositiveIntegerField()),
                ('des_province_name', models.CharField(max_length=50)),
                ('des_city', models.PositiveIntegerField()),
                ('des_city_name', models.CharField(max_length=50)),
                ('des_area', models.PositiveIntegerField()),
                ('des_area_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField()),
                ('start_range', models.PositiveSmallIntegerField()),
                ('end_range', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContractData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Customer')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Gear')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Line')),
            ],
            options={
                'db_table': 'tms_contract_data',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Customer'),
        ),
    ]
