# Generated by Django 2.2.1 on 2019-05-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_auto_20190519_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0, max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Company')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.UserProject')),
            ],
        ),
    ]
