# Generated by Django 2.2.1 on 2019-05-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_auto_20190521_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='carrier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Customer'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='carrier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier'),
        ),
        migrations.AlterField(
            model_name='contractdata',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Customer'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='carrier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Carrier'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tms.Customer'),
        ),
    ]
