# Generated by Django 2.2.1 on 2019-05-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_userproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProject',
            new_name='Project',
        ),
    ]
