# Generated by Django 2.2.1 on 2019-05-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_auto_20190521_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='level',
        ),
    ]
