# Generated by Django 2.2.1 on 2019-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_remove_project_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
