# Generated by Django 2.2.1 on 2019-05-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_auto_20190519_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.Project'),
        ),
    ]
